
FROM nvcr.io/nvidia/l4t-ml:r35.2.1-py3

# Update package lists and install dependencies
RUN apt-get update && \
    apt-get install -y curl git

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs

# Create an notebooks directory
RUN mkdir /notebooks

# Set the working directory to /app
WORKDIR /notebooks
